### ISSUE TITLE
Spherical coordinates kerfuffle

### ISSUE THREAD

**Issue by karlek** [mewmew/orbitals#1]
Isn't `\theta` bounded between `0 <= \theta <= \pi`?
https://en.wikipedia.org/wiki/Spherical_coordinate_system#Unique_coordinates
 
https://github.com/mewmew/orbitals/blob/32d6452be4915e44bb65f8060d857edbeabdcfe4/blender.go#L28

**Comment by mewmew** [comment]
Good kerfuffle catch!

**Comment by mewmew** [comment]
fixed in ![fluffy](https://user-images.githubusercontent.com/1278705/95737281-b8792f00-0c87-11eb-8dc5-9d6e61ce19c8.gif)
